services:
  - type: web
    name: cafeteria-backend
    env: docker
    plan: free
    region: oregon
    envVars:
      - key: PORT
        value: 8080
      - key: DB_USERNAME
        fromDatabase:
          name: cafeteria-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: cafeteria-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: cafeteria-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: cafeteria-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: cafeteria-db
          property: database

databases:
  - name: cafeteria-db
    databaseName: cafeteriagr
    user: cafeteria_user
    plan: free
    region: oregon
